# Generated by Django 5.1.2 on 2024-11-04 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login_App', '0001_initial'),
        ('Restaurantes_App', '0010_menurestaurantes_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosRestaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(help_text='Comentario del usuario', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.IntegerField(default=0, help_text='Puntaje del comentario', null=True)),
                ('restaurante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurantes_App.restaurantes')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Login_App.usuarios')),
            ],
        ),
    ]
