# Generated by Django 5.1.2 on 2024-10-20 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login_App', '0001_initial'),
        ('Restaurantes_App', '0003_delete_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(help_text='Pedido del restaurante', max_length=255)),
                ('precio', models.IntegerField(help_text='Precio del pedido')),
                ('fecha', models.DateTimeField(help_text='Fecha del pedido')),
                ('status', models.CharField(help_text='Estado del pedido', max_length=255)),
                ('ubicacionEntrega', models.CharField(help_text='Ubicación de entrega del pedido', max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_App.usuarios')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantes_App.restaurantes')),
            ],
        ),
    ]
