# Generated by Django 5.1.2 on 2024-10-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos_App', '0001_initial'),
        ('Restaurantes_App', '0004_menurestaurantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Restaurantes_App.menurestaurantes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='tiempoEstimado',
            field=models.IntegerField(help_text='Tiempo estimado para el pedido', null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedido',
            field=models.CharField(help_text='Pedido del restaurante', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(help_text='Estado del pedido', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ubicacionEntrega',
            field=models.CharField(help_text='Ubicación de entrega del pedido', max_length=255, null=True),
        ),
    ]
