# Generated by Django 5.1.2 on 2024-10-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos_App', '0003_alter_pedidos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='tiempoEstimado',
            field=models.DateTimeField(help_text='Tiempo estimado para el pedido que quiere el cliente', null=True),
        ),
    ]
