# Generated by Django 5.1.2 on 2024-10-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos_App', '0004_remove_pedidos_pedido_alter_pedidos_tiempoestimado'),
        ('Restaurantes_App', '0006_alter_menurestaurantes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='menu',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='menuCount',
            field=models.ManyToManyField(help_text='Cantidad de pedidos que quiere el cliente', related_name='pedidos', to='Restaurantes_App.menurestaurantes'),
        ),
    ]
