# Generated by Django 5.1.2 on 2024-10-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos_App', '0005_remove_pedidos_menu_pedidos_menucount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='menuCount',
            new_name='menus',
        ),
    ]
