# Generated by Django 5.1.2 on 2024-10-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
