# Generated by Django 5.1.2 on 2024-10-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0002_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
