# Generated by Django 5.1.2 on 2024-10-20 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0003_delete_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRestaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Titulo del menu', max_length=255)),
                ('nombre', models.CharField(help_text='Nombre del menu', max_length=255)),
                ('precio', models.IntegerField(help_text='Precio del menu')),
                ('fecha', models.DateTimeField(help_text='Fecha del menu')),
                ('status', models.CharField(help_text='Estado del menu', max_length=255)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='images/')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantes_App.restaurantes')),
            ],
        ),
    ]
