# Generated by Django 5.1.2 on 2024-10-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0005_alter_menurestaurantes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestaurantes',
            name='status',
            field=models.BooleanField(default=False, help_text='Estado del menu'),
        ),
    ]
