# Generated by Django 5.1.2 on 2024-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0006_alter_menurestaurantes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestaurantes',
            name='fecha',
            field=models.CharField(help_text='Fecha del menu', max_length=255),
        ),
    ]
