# Generated by Django 5.1.2 on 2024-10-20 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRestaurantes_App', '0001_initial'),
        ('Restaurantes_App', '0007_alter_menurestaurantes_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantes',
            name='usarioRestaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoginRestaurantes_App.restaurantesusuarios'),
        ),
    ]
