# Generated by Django 5.1.2 on 2024-11-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0009_rename_usariorestaurante_restaurantes_usuariorestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurestaurantes',
            name='descripcion',
            field=models.CharField(help_text='Descripción del menu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menurestaurantes',
            name='puntaje',
            field=models.IntegerField(help_text='Puntaje del menu', null=True),
        ),
    ]
