# Generated by Django 5.1.2 on 2024-11-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantes_App', '0010_menurestaurantes_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menurestaurantes',
            name='precio',
            field=models.FloatField(help_text='Precio del menu'),
        ),
    ]
