# Generated by Django 5.1.2 on 2024-11-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRestaurantes_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantesusuarios',
            name='isCliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantesusuarios',
            name='isRestaurante',
            field=models.BooleanField(default=True),
        ),
    ]
