# Generated by Django 5.1.2 on 2024-11-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='isCliente',
            field=models.BooleanField(default=True),
        ),
    ]
